- name: frontend server
  hosts: all
  become: yes
  tasks:
    - name: nginx server installation
      ansible.builtin.dnf:
        name: nginx
        state: latest



    - name: start Nginx 
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
