- name: frontend server
  hosts: all
  become: yes
  tasks:
    - name: nginx server installation
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: copy expense configuration
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: clean up the old content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: start Nginx 
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
