- name: backend setup
  hosts: all
  become: yes
  tasks:
    - name: DNF mysql installation
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: start the backend service
      ansible.builtin.systemd_service:
        state: restarted
        name: mysqld
        enabled: yes

    - name: start the backend service
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1