- name: demo on vars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
      - name: print variable
        ansible.builtin.debug:
          msg: URL_PLAY ="{{URL_PLAY}}"

      - name: print task variable

        ansible.builtin.debug:
          msg: url_task_variable ="{{url_task_variable}}"
        vars:
          url_task_variable: play.task.com
